version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: med_inventory
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    command: sh -c "npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/med_inventory
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
